---
- hosts: localhost

  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: apps-rg
      location: eastus

  - name: Create storage account
    azure_rm_storageaccount:
      resource_group: apps-rg
      name: appstr
      account_type: Standard_LRS
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: apps-rg
      name: appvnet
      address_prefixes: "10.10.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: apps-rg
      name: appsubnet
      address_prefix: "10.10.0.0/24"
      virtual_network: appvnet
  - name: Create public ip
    azure_rm_publicipaddress:
      resource_group: apps-rg
      allocation_method: Static
      name: apppip
  - name: Create security group that allows SSH
    azure_rm_securitygroup:
      resource_group: apps-rg
      name: appsg
      rules:
      - name: allowall
        protocol: Tcp
        destination_port_range: "*"
        access: Allow
        priority: 101
        direction: Inbound
  - name: Create NIC
    azure_rm_networkinterface:
      resource_group: apps-rg
      name: appnic
      virtual_network: appvnet
      subnet: appsubnet
      public_ip_name: apppip
      security_group: appsg
  - name: Create virtual machine
    azure_rm_virtualmachine:
      resource_group: apps-rg
      name: appvm
      vm_size: Standard_D2s_v3
      admin_username: vmadmin
      admin_password: April@123456789
      network_interfaces: appnic
      image:
       offer: UbuntuServer
       publisher: Canonical
       sku: '18.04-LTS'
       version: latest
